/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package praktikum3;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Q
 */
public class perpustakaan extends javax.swing.JFrame {
    
    String pilihan=" ";
    String ket;
    String nama ;
    String identitas ;
    String telepon;
    String tampilkan;
    int pilih;

    /**
     * Creates new form perpustakaan
     */
    public perpustakaan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        noidentitas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtnotelepon = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cpilih = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        bpilih = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtket = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(204, 0, 51));

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.setLayout(new java.awt.GridLayout(5, 2));

        jLabel1.setText("NAMA");
        jPanel1.add(jLabel1);

        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });
        jPanel1.add(txtnama);

        jLabel3.setText("NO IDENTITAS");
        jPanel1.add(jLabel3);

        noidentitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noidentitasActionPerformed(evt);
            }
        });
        jPanel1.add(noidentitas);

        jLabel4.setText("NO TELEPON");
        jPanel1.add(jLabel4);

        txtnotelepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnoteleponActionPerformed(evt);
            }
        });
        jPanel1.add(txtnotelepon);

        jLabel2.setText("PILIH BUKU");
        jPanel1.add(jLabel2);

        cpilih.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Buku", "Buku Great At Work", "Catatan Kronik", "Marriage with Benefit", "Detektif Conan", "21 Pelajaran Abad 21", "Tereliye Bumi", "Filosofi Teras" }));
        cpilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpilihActionPerformed(evt);
            }
        });
        jPanel1.add(cpilih);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        bpilih.setText("PINJAM");
        bpilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpilihActionPerformed(evt);
            }
        });

        bhapus.setText("HAPUS");
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("PERPUSTAKAAN ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(80, 80, 80))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bpilih, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bpilih, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(233, Short.MAX_VALUE))
        );

        txtket.setColumns(20);
        txtket.setRows(5);
        jScrollPane1.setViewportView(txtket);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                .addGap(25, 25, 25))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(255, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cpilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpilihActionPerformed
        pilihan = (String) cpilih.getSelectedItem();
        switch (pilihan) {
            case "Buku Great At Work":
            ket = "Penulis : TereLiye"+"\nPenerbit : Gramedia"+"\nJumlah Hal : 512"+"\nTahun Terbit : 2019"+
            "\nKita Sering Mendengar Istilah Work, "
            + "\nsmart, tetapi kita tidak banyak yang tahu maksudnya";
            break;
            case "Catatan Kronik":
            ket = "Penulis : Ida Iskandar"+"\nPenerbit : Dunia Buku"+"\nJumlah Hal : 409"+"\nTahun Terbit : 2020"+
            "\nBuku Kumpulan puisi yang seluruh isinya"
            + "\nterinspirasi dari kisah kehidupan pencipta buku.";
            break;
            case "Marriage with Benefit":
            ket = "Penulis : TereLiye"+"\nPenerbit : Gramedia"+"\nJumlah Hal : 440"+"\nTahun Terbit : 2019"+
            "\nmenikah Dengan Wanita Seorang gurbernur?!";
            break;
            case "Detektif Conan":
            ket = "Penulis : Kasasi Kisimoto"+"\nPenerbit : Sinar B"+"\nJumlah Hal : 207"+"\nTahun Terbit : 2010"+
            "\nSeorang Dengan kemampuan "
            + "\ndetektifnya yang sangat hebat.";
            break;
            case "Pelajaran Abad 21":
            ket = "Penulis : Johnson G"+"\nPenerbit : Gramedia"+"\nJumlah Hal : 512"+"\nTahun Terbit : 2019"+
            "\nRangkuman Pelajaran untuk Abad 21 "
            + "\nkarena perubah teknologi, dsb.";
            break;
            case "Tereliye Bumi":
            ket = "Penulis : TereLiye"+"\nPenerbit : Gramedia"+"\nJumlah Hal : 602"+"\nTahun Terbit : 2017"+
            "\nSeorang Manusia bumi memiliki kekuatan "
            + "\ntersembunyi?, ikuti kisahnya!";
            break;
            case "Filosofi Teras":
            ket = "Penulis : TereLiye"+"\nPenerbit : Gramedia"+"\nJumlah Hal : 428"+"\nTahun Terbit : 2020"+
            "\nBuku yang selalu diminati karena "
            + "\nterkandung filosofi kehisupan penuh makna.";
            break;
        }
        txtket.setText(""+ket);

        pilih = cpilih.getSelectedIndex();
        if(pilih==1){
            jPanel3.setBackground(Color.GREEN);
            jPanel4.setBackground(Color.GREEN);
        }
        if(pilih==2){
            jPanel3.setBackground(Color.YELLOW);
            jPanel4.setBackground(Color.YELLOW);
        }
        if(pilih==3){
            jPanel3.setBackground(Color.ORANGE);
            jPanel4.setBackground(Color.ORANGE);
        }
        if(pilih==4){
            jPanel3.setBackground(Color.BLUE);
            jPanel4.setBackground(Color.BLUE);
        }
        if(pilih==5){
            jPanel3.setBackground(Color.PINK);
            jPanel4.setBackground(Color.PINK);
        }
        if(pilih==6){
            jPanel3.setBackground(Color.RED);
            jPanel4.setBackground(Color.RED);
        }
        if(pilih==7){
            jPanel3.setBackground(Color.BLACK);
            jPanel4.setBackground(Color.BLACK);
        }

        nama      = txtnama.getText();
        identitas = noidentitas.getText();
        telepon   = txtnotelepon.getText();

        SimpleDateFormat tanggal = new SimpleDateFormat("dd-MM-yyyy"); // Format tanggal
        Date tanggalSaatIni = new Date();
        tampilkan = tanggal.format(tanggalSaatIni);
        txtket.setEditable(false);
    }//GEN-LAST:event_cpilihActionPerformed

    private void bpilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpilihActionPerformed
        JOptionPane.showMessageDialog(this, "Nama Anda : " +nama + "\nNo Identias  : " +identitas + "\nBuku yang dipinjam : " +pilihan  + "\nTanggal Pinjam :  "+tampilkan );

    }//GEN-LAST:event_bpilihActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed

        txtnama.setText("");
        noidentitas.setText("");
        txtnotelepon.setText("");
        cpilih.setSelectedIndex(0);
        txtket.setText("");
    }//GEN-LAST:event_bhapusActionPerformed

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void noidentitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noidentitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noidentitasActionPerformed

    private void txtnoteleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnoteleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnoteleponActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new perpustakaan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bpilih;
    private javax.swing.JComboBox<String> cpilih;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField noidentitas;
    private javax.swing.JTextArea txtket;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnotelepon;
    // End of variables declaration//GEN-END:variables
}
